version: "3"
services:
    web:
      build: .
      ports:
        - "8080:8080" 
      depends_on: 
        - postgres   
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"